### ISSUE TITLE
Error after 1 minute.

### ISSUE THREAD

**Issue by 4rzael** [anthill/pheromon#43]
I tried pheromon on my computer, and after exactly 1 minute, it shows me these errors:

```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/code/build/docker-compose/out00-PYZ.pyz/threading", line 810, in __bootstrap_inner
  File "/code/build/docker-compose/out00-PYZ.pyz/threading", line 763, in run
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.multiplexer", line 41, in _enqueue_output
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.log_printer", line 59, in _make_log_generator
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.utils", line 99, in split_buffer
  File "/code/build/docker-compose/out00-PYZ.pyz/docker.clientbase", line 236, in _stream_raw_result
  File "/code/build/docker-compose/out00-PYZ.pyz/requests.utils", line 332, in stream_decode_response_unicode
  File "/code/build/docker-compose/out00-PYZ.pyz/requests.models", line 680, in generate
ConnectionError: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out.

Exception in thread Thread-4:
Traceback (most recent call last):
  File "/code/build/docker-compose/out00-PYZ.pyz/threading", line 810, in __bootstrap_inner
  File "/code/build/docker-compose/out00-PYZ.pyz/threading", line 763, in run
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.multiplexer", line 41, in _enqueue_output
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.log_printer", line 59, in _make_log_generator
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.utils", line 99, in split_buffer
  File "/code/build/docker-compose/out00-PYZ.pyz/docker.clientbase", line 236, in _stream_raw_result
  File "/code/build/docker-compose/out00-PYZ.pyz/requests.utils", line 332, in stream_decode_response_unicode
  File "/code/build/docker-compose/out00-PYZ.pyz/requests.models", line 680, in generate
ConnectionError: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out.

Exception in thread Thread-3:
Traceback (most recent call last):
  File "/code/build/docker-compose/out00-PYZ.pyz/threading", line 810, in __bootstrap_inner
  File "/code/build/docker-compose/out00-PYZ.pyz/threading", line 763, in run
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.multiplexer", line 41, in _enqueue_output
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.log_printer", line 59, in _make_log_generator
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.utils", line 99, in split_buffer
  File "/code/build/docker-compose/out00-PYZ.pyz/docker.clientbase", line 236, in _stream_raw_result
  File "/code/build/docker-compose/out00-PYZ.pyz/requests.utils", line 332, in stream_decode_response_unicode
  File "/code/build/docker-compose/out00-PYZ.pyz/requests.models", line 680, in generate
ConnectionError: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out.
```

It doesn't seems to affect pheromon (everything works fine), but I thought it was strange.

Any idea why it does this ?

**Comment by iOiurson** [comment]
There's an older issue about it #36. Closing this one.
